from collections import Counter


ciphertext = "HEINSTASENTTSIFIOREGTHEUFUTTEOEFTRHNTEERINSNEOWTDDERCLNADDNUREIALCIVGEATHATHTSOBUTEHSOWUTYHSTEINETACETIRVESATIFVONCMALRTESNTHHEAGKIPNIRLECDTTOATHYEERNICMAEOFPLPERTIHEOFSTETIRMINLCESFEIHNGETCORUNETINEJUYNFLYASOTARWSNEOENKTODOHEOOPTPTUYNIRTOREEITTATSEHRITRLONSGHEELDYBIEAFTLHOUDRFTERAVLGEORNTMEENASNBUHRDTAHEEPCHTMERNNWHHIOCURRFOOUHADMETNENGTRMITSROFHFEDNOMEADERMODCCYEWEARRARNSTCBEODBIYRFFORUETHCERASNTEUREIAGGORSERDSLEASFYTOUORKENONASWDIENOHSASGASIUSMTAJSLLPCHAAERLINTARGTERASRYNTHOEGHFTBIEREWSNOOENPSADPAREANECHENCBTSWSWSHEOIXITYSMUTIESNAEDVARRITINNGEAFRTIGDHNIXNGEEOSDEOPNTAKBRAORSAOREGIZOATNISTCHANTLLAECOTALAYSNEDSOELNLRPOERUSALOINNFMANTIROSAMCOAMDIETYOWENUOTRJTTIALSKGELMANIANNDCSOACSTLTISWTERTELKOINAGRMCEDUITIHONASBINTSAADAAILDYTIIVICTSLYESETUTKHIONATOABDREREINKGISSTSXAFREINAGNDRUSITMAPDEYUFADFEOWRETLIECANUDFSRTRDATSEORHMEFRCKTERASETHRUHTSDBATIAOKNERRIISGAHGUINTDUESYCIONRSTIFNGSOHONUSTASOMFCDOANBIEPSYINNGUASENLLDIOUIRPGRACAYTVOVESRTDIRSGTHEEVEERNOMTATNDNOERKBRHORSGTHEEVEERNOMTDNOENSDRTIVTEISUINHDTRMYASSCHIASUWLIYNGLLARITIPCATTEWPIINHITHTREUALEGLTRYPIAIEESATRHEERETSRCSHEARDVIERATERDSASNNTEERINCONMPTAESEWHIOCOGURNASUECHEBAVIIOHRNOATSFTETRHETIINIANFCLRNEVAEEMLODUENTLIREEUPTONYIIXITYSMUTOESNFEXLAMRPPOEINETOUWTHDOHEGLATRSTADAETROHKEBRSCEOLALTEADOCNERFAGVEFTHEEINNDTREUDDBOITISINMFOFRTINONAOORAETMHTWNOHNURELDMDIIOENALMICTANRSESEEAHROTPSUNSCTEEDETROTRIRSBUTTRSAERREVHEDATYCYIZEANSIHINEGTVHRONNLIIDIEAREISONLDSUERTNEDATHIEMHWHOHUTTTIRWKNEOEDRGELOPPAROAVASSTHLIITIUASTNCSOMOEOLTIGTHVERNFEUHEMRWTESTOASUKRSEELUVTWEOQSUTIAONSSEWAEORKHAGVIYNURIONOLEAVCTNITINESIACONNTDEMIANETDDMIORNEPONRTMAWHAATTCWEBDONAUTNITOSWDNENOAOTSHEDRRGHUEATTTEHEABTWOEASPWOBULNDANOEWEWLDEINRTNEDTORRRIINWEHHEONDCTNDRENECPTSIOYNLUNTIOOMAHKESTMEEANESPLDOYMEYTSHEBNANHDOATRSOIMEPSIBLSE"

# === Overall Letter Frequency (%)
def letter_freq(text):
    total = len(text)
    count = Counter(text)
    return {k: round(v / total * 100, 2) for k, v in sorted(count.items())}

# === Index of Coincidence
def index_of_coincidence(text):
    N = len(text)
    freqs = Counter(text)
    return sum(f * (f - 1) for f in freqs.values()) / (N * (N - 1))

# === Segment-based IC for period testing
def segment_ic(text, period):
    segments = ['' for _ in range(period)]
    for i, c in enumerate(text):
        segments[i % period] += c
    return sum(index_of_coincidence(s) for s in segments) / period

# === Run Analysis
print("📊 Letter Frequency Distribution (%):")
for k, v in letter_freq(ciphertext).items():
    print(f"{k}: {v}")

print(f"\n🧮 Overall IC: {round(index_of_coincidence(ciphertext), 5)}")

print("\n🔍 Segment-wise IC Averages (Testing periods 5–10):")
for p in range(5, 11):
    ic = segment_ic(ciphertext, p)
    print(f"Period {p}: Avg Segment IC = {round(ic, 5)}")
