import wordninja
import textwrap

# Paste the glued plaintext here
text = "Thensaissettingfiretothefutureoftheinternetsnowdendeclaredduringalivechatatthesouthbysouthwestinteractivefestivalonmarchtenthspeakingdirectlytotheamericanpeopleforthefirsttimesincefleeingthecountryinjuneoflastyearsnowdentooktheopportunitytoreiteratehisstronglyheldbeliefthatourfederalgovernmenthasburnedtheparchmentonwhichourfourthamendmentrightsoffreedomanddemocracyweretranscribedbyourforefatherscenturiesagoregardlessofyourtakeonsnowdenhissagaisjustasmallchapterinalargerstorythenightbeforesnowdensappearancethecbsnewsshowsixtyminutesairedarivetingandfrighteningexposeondatabrokersorganizationsthatcollectanalyseandsellourpersonalinformationasacommoditywerenotjusttalkingemailsandcontactlistsweretalkingourmedicationshabitsanddailyactivitieslestyouthinkdatabrokeringexistsasafringeindustrymadeupofafewderelictsandfrustratedformerhackersthetruthisdatabrokeringisahugeindustryconsistingofthousandsofcompaniesbuyingandsellingourprivacytoadvertisersthegovernmentandotherbrokersthegovernmentdoesntdrivethisindustryasmuchaswillinglyparticipatewithinittherealguiltypartiesaretheresearchersadvertisersandinternetcompanieswhoencouragesuchbehaviorifnotstatetheirfinancialrevenuemodelentirelyuponitsixtyminutesforexamplepointedouthowthelargestdatabrokerhascollectedonaveragefifteenhundredtidbitsofinformationonmorethantwohundredmillionamericansthesearenotsuspectedterroristsbutrathereverydaycitizenshavingtheironlinediariessoldunderneaththemwithouttheirknowledgeorapprovalasthissituationcomestolightevenfurtherwemustaskourselvestwoquestionsareweokayhavingouronlineactivitiesandcontentminedandmoreimportantwhatcanwedoaboutitsnowdenandothersarguethatthebestweaponwouldbeanewworldinternetorderinwhichendtoendencryptionsolutionsmakethemeansemployedbythensaandothersimpo"
# Use wordninja to split into likely English words
words = wordninja.split(text)

# Join and wrap to 80 characters per line
formatted = textwrap.fill(' '.join(words), width=80)
print(formatted)

