import wordninja
import textwrap

decrypted_text = (
    "THEBACKDOORMALWAREDISCOVEREDONASERVERATAUSMANUFACTURINGCOMPANYWASSPOTTEDANDCLEANEDUPWITHINTWENTYFOURHOURSOFITSIMPLANTATIONANDBYALLACCOUNTSTHATPARTICULARCYBERESPIONAGEATTACKHADBEENTHWARTEDBUTTHENEXTDAYTWONEWBACKDOORSWERESPOTTEDONTWOOTHERSERVERSANDTHECOMPANYREALIZEDITSINCIDENTRESPONSEOPERATIONHADNOTBEENSOSUCCESSFULAFTERALLWEKNEWTHETROJANONTHATFIRSTSYSTEMBUTWEMISSEDOUTONACOUPLEOFOTHERMACHINESASSOONASWECLEANEDUPTHEONEMACHINETHERETHEYWERETHENEXTDAYSAYSTHEIRSECURITYTEAMMEMBERATTHEMANUFACTURINGFIRMWHOSPOKEONTHECONDITIONTHATHISCOMPANYNOTBENAMEDTHEYHADMOVEDLATERALLYANDINSTALLEDTWOCOMPLETELYDIFFERENTBACKDOORSSOIOCSINDICATORSOFCOMPROMISESIGNATURESWEREUSELESSWEMADEADECISIONTOOQUICKLYYOUHAVETOBEQUICKANDTHOROUGHTHISWASALEARNINGLESSONFORUSNOWTHATORGANIZATIONSANDTHESECURITYINDUSTRYFORTHEMOSTPARTHAVEACCEPTEDTHEUGLYTRUTHTHATBREACHESAREINEVITABLEANDTHEBADGUYSAREGOINGTOFINDAWAYTOGETINSIDETHENEWFOCUSISONHOWYOURESPONDTOANATTACKORATTACKATTEMPTANDMINIMIZETHEDAMAGEMEGARETAILERTARGETSMISSTEPSINITSPOSTBREACHOPERATIONHAVEDRIVENHOMEANEWSENSEOFURGENCYINESTABLISHINGASOLIDINCIDENTRESPONSEOPERATIONTHATISASMUCHABOUTPROTECTINGDATAASITISABOUTPROTECTINGTHECORPORATEIMAGEINCIDENTRESPONSEIRISBECOMINGPARTANDPARCELOFASECURITYSTRATEGYEXPERTSSAYMORETHANSIXTYPERCENTOFORGANIZATIONSSAYTHEYHAVEIRPLANSINPLACEACCORDINGTOARECENTREPORTBYARBORNETWORKSANDTHEECONOMISTINTELLIGENCEUNITWHICHSURVEYEDSOMETHREEHUNDREDSIXTYCLEVELORBOARDLEVELBUSINESSEXECUTIVESAROUNDTHEGLOBEONTHEIRINCIDENTRESPONSEPOSTURESACCORDINGTOTHEDATAAROUNDTWOTHIRDSOFTHEORGANIZATIONSSAYASUCCESSFULANDSMOOTHINCIDENTRESPONSEOPERATIONINTHEFACEOFABREACHCOULDULTIMATELYENHANCETHEIRREPUTATIONTHESAVINGFACEPIECEISBIGSAYSDANHOLDENDIRECTOROFARBORSASERT"

)

# === 1. Use wordninja to add spaces ===
words = wordninja.split(decrypted_text.lower())

# === 2. Capitalize sentences (basic rule-based approach) ===
# Capitalize after a period + split into lines
sentences = []
sentence = []
for word in words:
    sentence.append(word)
    if word.endswith('.') or word in ['but', 'and', 'however']:
        sentences.append(' '.join(sentence).capitalize())
        sentence = []


if sentence:
    sentences.append(' '.join(sentence).capitalize())

formatted = "\n\n".join(textwrap.fill(s, width=80) for s in sentences)


print("Formatted Decrypted Text:\n")
print(formatted)


